import { Link, NavLink } from 'react-router-dom';
import { Menu, X, ArrowUp, MessageCircle } from 'lucide-react';
import { useEffect, useState } from 'react';
import { navLinks } from '../utils/data';
export default function Layout({children}){
  const [open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),[progress,setProgress]=useState(0);
  useEffect(()=>{const on=()=>{setScrolled(window.scrollY>20); const h=document.documentElement; setProgress((h.scrollTop/(h.scrollHeight-h.clientHeight))*100)}; window.addEventListener('scroll',on); on(); return()=>window.removeEventListener('scroll',on)},[]);
  return <div><div className='fixed top-0 left-0 h-1 bg-gold z-[80]' style={{width:`${progress}%`}}/><header className={`fixed w-full z-50 transition-all ${scrolled?'bg-white/90 shadow-premium backdrop-blur':'bg-transparent'}`}><nav className='section py-4 flex items-center justify-between'><Link to='/' className='font-heading text-2xl'>VAgeWell</Link><div className='hidden md:flex gap-6'>{navLinks.map(([u,l])=><NavLink key={u} to={u} className='hover:text-sage'>{l}</NavLink>)}</div><Link to='/admission' className='hidden md:block bg-sage text-white px-5 py-2 rounded-full'>Book a Visit</Link><button className='md:hidden' onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className='md:hidden bg-white px-6 pb-6 space-y-3'>{navLinks.map(([u,l])=><NavLink key={u} to={u} onClick={()=>setOpen(false)} className='block'>{l}</NavLink>)}</div>}</header><main className='pt-24'>{children}</main><footer className='bg-charcoal text-beige'><div className='section grid md:grid-cols-4 gap-8'><div><h4 className='font-heading text-2xl'>VAgeWell</h4><p>Caring for Every Golden Year.</p></div><div><h5>Quick links</h5>{navLinks.slice(0,5).map(([u,l])=><Link key={u} to={u} className='block'>{l}</Link>)}</div><div><h5>Services</h5><p>Assisted Living · Wellness · Dementia Care</p></div><div><h5>Newsletter</h5><input className='w-full mt-2 p-2 rounded text-charcoal' placeholder='Your email'/></div></div><div className='text-center py-4 border-t border-white/10'>VAgeWell — Caring for Every Golden Year.</div></footer><a href='https://wa.me/10000000000' className='fixed bottom-24 right-5 bg-green-500 text-white p-3 rounded-full'><MessageCircle/></a><button onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} className='fixed bottom-6 right-5 bg-sage text-white p-3 rounded-full'><ArrowUp/></button></div>
}
